import { CommonModule } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
type Page='dashboard'|'apis';
interface ApiItem{id:string;name:string;summary:string;method:string;path:string;type:string;status:string;version:string;protocol:string;auth:string;fields:{name:string;description:string}[];sampleBody:Record<string,string>}
interface Connection{hospitalId:string;userName:string;fullName:string;domain:string;expiresAt:string}
@Component({selector:'app-root',imports:[CommonModule,FormsModule],templateUrl:'./app.html',styleUrl:'./app.css'})
export class App implements OnInit{
 private cd=inject(ChangeDetectorRef);
 private http=inject(HttpClient);page:Page='dashboard';menuOpen=true;groups:Record<string,boolean>={tongquan:true,tichhop:true,hethong:true};apis:ApiItem[]=[];selected?:ApiItem;query='';statusFilter='all';sortAsc=true;apiKey='';connectionId=sessionStorage.getItem('hisConnectionId')||'';connection?:Connection;showLogin=false;login={domain:'',username:'',password:''};loginError='';loading=false;connecting=false;dashboardDate=this.dateInput(new Date());notice='Kết nối HIS và bấm Lấy dữ liệu để hiển thị Dashboard.';noticeOk=false;patients:any[]=[];departments:any[]=[];rooms:any[]=[];activities:{label:string;ok:boolean;detail:string}[]=[];
 async ngOnInit(){await this.bootstrap();this.cd.detectChanges()}
 get activeApis(){return this.apis.filter(x=>x.status==='Đang hoạt động').length}
 get filteredApis(){const q=this.query.trim().toLowerCase(),status:{[key:string]:string}={active:'Đang hoạt động',paused:'Tạm dừng',cancelled:'Đã hủy'};return this.apis.filter(x=>(this.statusFilter==='all'||x.status===status[this.statusFilter])&&(`${x.name} ${x.path}`.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'vi')*(this.sortAsc?1:-1))}
 get bedPlan(){return this.departments.reduce((s,x)=>s+Number(x.GiuongKeHoach||0),0)}get bedActual(){return this.departments.reduce((s,x)=>s+Number(x.GiuongThucKe||0),0)}get bedRatio(){return this.bedPlan?Math.min(100,Math.round(this.bedActual/this.bedPlan*100)):0}
 get receptions(){const map=new Map<string,any>();for(const[i,x]of this.patients.entries()){const key=String(x.TIEPNHANID??x.TiepNhanId??x.MABENHNHAN??i);if(!map.has(key))map.set(key,x)}return[...map.values()]}
 get departmentBars(){const map=new Map<string,number>();for(const x of this.receptions){const name=this.pick(x,['TENKHOA_BD','TenKhoaBd','TENKHOA','TenKhoa','KHOABATDAU','TENKHOABATDAU'])||'Chưa xác định';map.set(name,(map.get(name)||0)+1)}const rows=[...map].sort((a,b)=>b[1]-a[1]).slice(0,8),max=Math.max(...rows.map(x=>x[1]),1);return rows.map(([name,value])=>({name,value,width:Math.max(2,value/max*100)}))}
 get roomBars(){const map=new Map<string,number>();for(const x of this.rooms){const name=String(x.TenKhoa||'Chưa xác định');map.set(name,(map.get(name)||0)+1)}const rows=[...map].sort((a,b)=>b[1]-a[1]).slice(0,6),max=Math.max(...rows.map(x=>x[1]),1);return rows.map(([name,value])=>({name,value,width:Math.max(2,value/max*100)}))}
 get outpatientCount(){return this.receptions.filter(x=>Number(x.LOAIBENHANID??x.LoaiBenhAnId)===23).length}get otherPatientCount(){return Math.max(0,this.receptions.length-this.outpatientCount)}get outpatientRatio(){return this.receptions.length?Math.round(this.outpatientCount/this.receptions.length*100):0}
 get hourlySeries(){const values=Array.from({length:24},(_,hour)=>({hour,value:0}));for(const x of this.receptions){const text=String(x.NGAYTIEPNHAN??x.NgayTiepNhan??''),match=text.match(/\s(\d{2}):/);if(match)values[Number(match[1])].value++}return values}get hourlyPoints(){const max=Math.max(...this.hourlySeries.map(x=>x.value),1);return this.hourlySeries.map((x,i)=>`${i/23*100},${92-x.value/max*75}`).join(' ')}get hourlyAreaPoints(){return`0,100 ${this.hourlyPoints} 100,100`}get peakHour(){return this.hourlySeries.reduce((best,x)=>x.value>best.value?x:best,{hour:0,value:0})}
 get todayLabel(){return new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}get maskedKey(){return this.apiKey?'••••••••••••':'Cấp riêng'}
 nav(page:Page){this.page=page;this.selected=undefined;location.hash=page}toggleGroup(group:string){this.groups[group]=!this.groups[group]}cycleFilter(){const values=['all','active','paused','cancelled'];this.statusFilter=values[(values.indexOf(this.statusFilter)+1)%values.length]}format(value:number){return new Intl.NumberFormat('vi-VN').format(value||0)}
 private dateInput(d:Date){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}private reportDate(){const[y,m,d]=this.dashboardDate.split('-');return`${d}/${m}/${y}`}private pick(row:any,names:string[]){for(const n of names)if(row?.[n]!=null&&String(row[n]).trim())return row[n];return''}private headers(){return new HttpHeaders({'Content-Type':'application/json','X-API-Key':this.apiKey,'X-HIS-Connection-Id':this.connectionId})}private async post(path:string,body:unknown={}){return await this.http.post<any>(path,body,{headers:this.headers()}).toPromise()}
 async bootstrap(){try{const catalog=await this.http.get<any>('/api/catalog').toPromise();this.apis=catalog.data||[];const key=await this.http.get<any>('/api/admin/api-key').toPromise();this.apiKey=key.apiKey||''}catch{}await this.refreshConnection();this.page=location.hash==='#apis'?'apis':'dashboard';this.clearDashboard()}
 async refreshConnection(){try{if(!this.apiKey||!this.connectionId)throw new Error();const out=await this.http.get<any>('/api/v1/connections/current',{headers:this.headers()}).toPromise();this.connection=out.data}catch{this.connection=undefined;this.connectionId='';sessionStorage.removeItem('hisConnectionId')}}
 async connect(){if(this.connecting)return;this.loginError='';this.connecting=true;try{const out=await this.http.post<any>('/api/v1/connections',this.login,{headers:new HttpHeaders({'Content-Type':'application/json','X-API-Key':this.apiKey})}).toPromise();this.connectionId=out.data.connectionId;sessionStorage.setItem('hisConnectionId',this.connectionId);this.login.password='';await this.refreshConnection();this.showLogin=false;this.clearDashboard()}catch(e:any){this.loginError=e?.error?.error?.message||'Không thể kết nối HIS'}finally{this.connecting=false;this.cd.detectChanges()}}
 async logout(){try{await this.http.delete('/api/v1/connections/current',{headers:this.headers()}).toPromise()}catch{}this.connection=undefined;this.connectionId='';sessionStorage.removeItem('hisConnectionId');this.clearDashboard();this.cd.detectChanges()}
 clearDashboard(){this.patients=[];this.departments=[];this.rooms=[];this.activities=[];this.noticeOk=false;this.notice='Kết nối HIS và bấm Lấy dữ liệu để hiển thị Dashboard.'}
 async loadDashboard(){if(!this.connection){this.clearDashboard();return}this.loading=true;this.notice='Đang lấy dữ liệu từ các API hiện có...';this.noticeOk=false;const sources=[{key:'patients',label:'Tiếp đón theo ngày',run:()=>this.post('/api/v1/reports/benh-nhan-tiep-don-ngay',{ngaytiepnhan:this.reportDate()})},{key:'departments',label:'Danh mục khoa',run:()=>this.post('/api/v1/catalogs/khoa')},{key:'rooms',label:'Danh mục phòng',run:()=>this.post('/api/v1/catalogs/phong')}];const results=await Promise.all(sources.map(async s=>{try{const out=await s.run();return{...s,ok:true,data:out.data||[],detail:`${this.format(out.meta?.count??out.data?.length??0)} bản ghi`}}catch(e:any){return{...s,ok:false,data:[],detail:e?.error?.error?.message||'Không tải được dữ liệu'}}}));for(const r of results)(this as any)[r.key]=r.data;this.activities=results.map(r=>({label:r.label,ok:r.ok,detail:r.detail}));const failed=results.filter(x=>!x.ok).length;this.noticeOk=!failed;this.notice=failed?`${failed} nguồn dữ liệu chưa tải được.`:`Đã cập nhật 3 nguồn dữ liệu lúc ${new Date().toLocaleTimeString('vi-VN')}`;this.loading=false;this.cd.detectChanges()}
 runApi(api:ApiItem){this.selected=api}async copySnippet(){await navigator.clipboard.writeText(this.snippet())}snippet(){if(!this.selected)return'';const connection=this.selected.id==='his-connection'?'':`\nX-HIS-Connection-Id: ${this.connectionId||'<HIS_CONNECTION_ID>'}`;return`${this.selected.method} ${location.origin}${this.selected.path}\nX-API-Key: ${this.apiKey||'<API_KEY>'}${connection}\nContent-Type: application/json\n\n${JSON.stringify(this.selected.sampleBody,null,2)}`}
}
